services:
  coord:
    image: tobi-dkls-party
    command: |
      /usr/local/bin/msg-relay-svc
    environment:
      RUST_LOG: debug
      LISTEN: 0.0.0.0:8080
    ports:
      - 8080:8080

  tobi-server:
    image: tobi-dkls-party
    command: |
      /usr/local/bin/tobi-server serve
        # --storage /data
        --coordinator ws://coord:8080/v1/msg-relay
    environment:
      RUST_LOG: info
      AUTH_DISABLE: true
    ports:
      - 8083:8080
    volumes:
      - p1-data:/data

  cache:
    image: redis:latest
    ports:
      - 6379:6379
