# Use an official Python 3.10 image as a parent image
FROM python:3.10-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

ENV PORT=8000

# Make port <PORT> available to the world outside this container
EXPOSE $PORT

# Run node_server.py when the container launches
CMD ["python", "node_server.py"]
