version: "3"

services:
  node_server_1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - node_network

  node_server_2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
    networks:
      - node_network

  node_server_3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5002
    ports:
      - "5002:5002"
    networks:
      - node_network

  nginx_frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    networks:
      - node_network

  redis:
    image: redis:latest
    networks:
      - node_network

networks:
  node_network:
    driver: bridge
